### ISSUE TITLE
Auto select window

### ISSUE THREAD

**Issue by sirnex** [DizzyduckAR/BotIt#3]
Is there a way for me to make it auto set the window to NoxPlayer instead of doing a grab everytime?

**Comment by DizzyduckAR** [comment]
oui

on any bot main.ahk

global targetwindow := "Grab & left Click" ;Window name

to
global targetwindow := "NoxPlayer" ;Window name

will default on "NoxPlayer" 

![AutoHotkeyU32_xRAKesI2DM](https://user-images.githubusercontent.com/52171360/77651844-99ed5980-6f2a-11ea-8550-e009f30b954a.png)
